// <auto-generated />
using System;
using BmeDashboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BmeDashboard.Migrations
{
    [DbContext(typeof(SensorDbContext))]
    [Migration("20260808222216_AddWeatherReadings1")]
    partial class AddWeatherReadings1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("BmeDashboard.Models.SensorReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("HumidityPercent")
                        .HasColumnType("REAL");

                    b.Property<double?>("PressureHpa")
                        .HasColumnType("REAL");

                    b.Property<double?>("TemperatureC")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SensorReadings");
                });

            modelBuilder.Entity("BmeDashboard.Models.WeatherReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("HumidityPercent")
                        .HasColumnType("REAL");

                    b.Property<double?>("PressureHpa")
                        .HasColumnType("REAL");

                    b.Property<double?>("TemperatureC")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeatherDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WeatherReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
